# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "3.6"

volumes:
  registry-data:
  couchdb0_data:
  couchdb1_data:
  couchdb2_data:
  couchdb3_data:
  couchdb4_data:

services:
  sawtooth-registry:
    image: registry:2
    container_name: sawtooth-registry
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_HTTP_SECRET=${REGISTRY_HTTP_SECRET}
    volumes:
      - ./registry-data:/var/lib/registry

  couch-db-0:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
      - ERL_FLAGS=-setcookie "${ERLANG_COOKIE}"
      - NODENAME=couch-db-0
    volumes:
      - couchdb0_data:/opt/couchdb/data
    ports:
      - "5984:5984"

  couch-db-1:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
      - ERL_FLAGS=-setcookie "${ERLANG_COOKIE}"
      - NODENAME=couch-db-1
    volumes:
      - couchdb1_data:/opt/couchdb/data
    ports:
      - "5985:5984"

  couch-db-2:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
      - ERL_FLAGS=-setcookie "${ERLANG_COOKIE}"
      - NODENAME=couch-db-2
    volumes:
      - couchdb2_data:/opt/couchdb/data
    ports:
      - "5986:5984"

  couch-db-3:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
      - ERL_FLAGS=-setcookie "${ERLANG_COOKIE}"
      - NODENAME=couch-db-3
    volumes:
      - couchdb3_data:/opt/couchdb/data
    ports:
      - "5987:5984"

  couch-db-4:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
      - ERL_FLAGS=-setcookie "${ERLANG_COOKIE}"
      - NODENAME=couch-db-4
    volumes:
      - couchdb4_data:/opt/couchdb/data
    ports:
      - "5988:5984"

  couchdb-setup:
    image: curlimages/curl:7.78.0
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    depends_on:
      - couch-db-0
      - couch-db-1
      - couch-db-2
      - couch-db-3
      - couch-db-4
    command: >
      sh -c "
      sleep 30 &&
      curl -X POST -H 'Content-Type: application/json' http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch-db-0:5984/_cluster_setup -d '{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\": \"$${COUCHDB_USER}\", \"password\":\"$${COUCHDB_PASSWORD}\", \"node_count\":\"5\"}' &&
      curl -X POST -H 'Content-Type: application/json' http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch-db-0:5984/_cluster_setup -d '{\"action\": \"add_node\", \"host\":\"couch-db-1\", \"port\": 5984, \"username\": \"$${COUCHDB_USER}\", \"password\":\"$${COUCHDB_PASSWORD}\"}' &&
      curl -X POST -H 'Content-Type: application/json' http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch-db-0:5984/_cluster_setup -d '{\"action\": \"add_node\", \"host\":\"couch-db-2\", \"port\": 5984, \"username\": \"$${COUCHDB_USER}\", \"password\":\"$${COUCHDB_PASSWORD}\"}' &&
      curl -X POST -H 'Content-Type: application/json' http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch-db-0:5984/_cluster_setup -d '{\"action\": \"add_node\", \"host\":\"couch-db-3\", \"port\": 5984, \"username\": \"$${COUCHDB_USER}\", \"password\":\"$${COUCHDB_PASSWORD}\"}' &&
      curl -X POST -H 'Content-Type: application/json' http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch-db-0:5984/_cluster_setup -d '{\"action\": \"add_node\", \"host\":\"couch-db-4\", \"port\": 5984, \"username\": \"$${COUCHDB_USER}\", \"password\":\"$${COUCHDB_PASSWORD}\"}' &&
      curl -X POST -H 'Content-Type: application/json' http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch-db-0:5984/_cluster_setup -d '{\"action\": \"finish_cluster\"}' &&
      sleep 10 &&
      for db in _users _replicator _global_changes; do
        for i in {0..4}; do
          curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch-db-$${i}:5984/$${db} || true;
        done;
      done &&
      sleep 5 &&
      curl -X GET http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch-db-0:5984/_all_dbs"

  fog-node-0:
    build:
      context: fog-node
      dockerfile: Dockerfile
    privileged: true
    image: sawtooth-registry:5000/fog-node:latest
    container_name: sawtooth-fog-node-0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - REGISTRY_URL=sawtooth-registry:5000
      - VALIDATOR_URL=tcp://validator-0:4004
      - NODE_ID=sawtooth-fog-node-0
      - COUCHDB_URL=http://couch-db-0:5984
    depends_on:
      - couch-db-0
      - validator-0
      - sawtooth-registry

  fog-node-1:
    build:
      context: fog-node
      dockerfile: Dockerfile
    privileged: true
    image: sawtooth-registry:5000/fog-node:latest
    container_name: sawtooth-fog-node-1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - REGISTRY_URL=sawtooth-registry:5000
      - VALIDATOR_URL=tcp://validator-1:4004
      - NODE_ID=sawtooth-fog-node-1
      - COUCHDB_URL=http://couch-db-1:5984
    depends_on:
      - couch-db-1
      - validator-1
      - sawtooth-registry

  fog-node-2:
    build:
      context: fog-node
      dockerfile: Dockerfile
    privileged: true
    image: sawtooth-registry:5000/fog-node:latest
    container_name: sawtooth-fog-node-2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - REGISTRY_URL=sawtooth-registry:5000
      - VALIDATOR_URL=tcp://validator-2:4004
      - NODE_ID=sawtooth-fog-node-2
      - COUCHDB_URL=http://couch-db-2:5984
    depends_on:
      - couch-db-2
      - validator-2
      - sawtooth-registry

  fog-node-3:
    build:
      context: fog-node
      dockerfile: Dockerfile
    privileged: true
    image: sawtooth-registry:5000/fog-node:latest
    container_name: sawtooth-fog-node-3
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - REGISTRY_URL=sawtooth-registry:5000
      - VALIDATOR_URL=tcp://validator-3:4004
      - NODE_ID=sawtooth-fog-node-3
      - COUCHDB_URL=http://couch-db-3:5984
    depends_on:
      - couch-db-3
      - validator-3
      - sawtooth-registry

  fog-node-4:
    build:
      context: fog-node
      dockerfile: Dockerfile
    privileged: true
    image: sawtooth-registry:5000/fog-node:latest
    container_name: sawtooth-fog-node-4
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - REGISTRY_URL=sawtooth-registry:5000
      - VALIDATOR_URL=tcp://validator-4:4004
      - NODE_ID=sawtooth-fog-node-4
      - COUCHDB_URL=http://couch-db-4:5984
    depends_on:
      - couch-db-4
      - validator-4
      - sawtooth-registry

  docker-image-client:
    build:
      context: auto-docker-deployment/docker-image-client
      dockerfile: Dockerfile
    privileged: true
    image: sawtooth-registry:5000/docker-image-client:latest
    container_name: sawtooth-docker-image-client
    environment:
      - VALIDATOR_URL=tcp://validator-0:4004
      - REGISTRY_URL=sawtooth-registry:5000
    volumes:
      - ./docker-images:/docker-images
    depends_on:
      - validator-0
      - sawtooth-registry
    command: tail -f /dev/null

  docker-image-tp-0:
    build:
      context: auto-docker-deployment/docker-image-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/docker-image-tp:latest
    container_name: sawtooth-docker-image-tp-0
    environment:
      - VALIDATOR_URL=tcp://validator-0:4004
    depends_on:
      - validator-0
      - sawtooth-registry
    stop_signal: SIGKILL

  docker-image-tp-1:
    build:
      context: auto-docker-deployment/docker-image-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/docker-image-tp:latest
    container_name: sawtooth-docker-image-tp-1
    environment:
      - VALIDATOR_URL=tcp://validator-1:4004
    depends_on:
      - validator-1
      - sawtooth-registry
    stop_signal: SIGKILL

  docker-image-tp-2:
    build:
      context: auto-docker-deployment/docker-image-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/docker-image-tp:latest
    container_name: sawtooth-docker-image-tp-2
    environment:
      - VALIDATOR_URL=tcp://validator-2:4004
    depends_on:
      - validator-2
      - sawtooth-registry
    stop_signal: SIGKILL

  docker-image-tp-3:
    build:
      context: auto-docker-deployment/docker-image-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/docker-image-tp:latest
    container_name: sawtooth-docker-image-tp-3
    environment:
      - VALIDATOR_URL=tcp://validator-3:4004
    depends_on:
      - validator-3
      - sawtooth-registry
    stop_signal: SIGKILL

  docker-image-tp-4:
    build:
      context: auto-docker-deployment/docker-image-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/docker-image-tp:latest
    container_name: sawtooth-docker-image-tp-4
    environment:
      - VALIDATOR_URL=tcp://validator-4:4004
    depends_on:
      - validator-4
      - sawtooth-registry
    stop_signal: SIGKILL

  peer-registry-tp-0:
    build:
      context: peer-registry/peer-registry-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/peer-registry-tp:latest
    container_name: sawtooth-peer-registry-tp-0
    environment:
      - VALIDATOR_URL=tcp://validator-0:4004
    depends_on:
      - validator-0
    stop_signal: SIGKILL

  peer-registry-tp-1:
    build:
      context: peer-registry/peer-registry-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/peer-registry-tp:latest
    container_name: sawtooth-peer-registry-tp-1
    environment:
      - VALIDATOR_URL=tcp://validator-1:4004
    depends_on:
      - validator-1
    stop_signal: SIGKILL

  peer-registry-tp-2:
    build:
      context: peer-registry/peer-registry-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/peer-registry-tp:latest
    container_name: sawtooth-peer-registry-tp-2
    environment:
      - VALIDATOR_URL=tcp://validator-2:4004
    depends_on:
      - validator-2
    stop_signal: SIGKILL

  peer-registry-tp-3:
    build:
      context: peer-registry/peer-registry-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/peer-registry-tp:latest
    container_name: sawtooth-peer-registry-tp-3
    environment:
      - VALIDATOR_URL=tcp://validator-3:4004
    depends_on:
      - validator-3
    stop_signal: SIGKILL

  peer-registry-tp-4:
    build:
      context: peer-registry/peer-registry-tp
      dockerfile: Dockerfile
    image: sawtooth-registry:5000/peer-registry-tp:latest
    container_name: sawtooth-peer-registry-tp-4
    environment:
      - VALIDATOR_URL=tcp://validator-4:4004
    depends_on:
      - validator-4
    stop_signal: SIGKILL