volumes:
  poet-shared:

services:

  shell:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  validator-0:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-0
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        if [ -e /poet-shared/validators/validator-0.priv ]; then
          cp /poet-shared/validators/validator-0.pub /etc/sawtooth/keys/validator.pub
          cp /poet-shared/validators/validator-0.priv /etc/sawtooth/keys/validator.priv
        fi
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /poet-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /poet-shared/validators/validator-0.pub
          cp /etc/sawtooth/keys/validator.priv /poet-shared/validators/validator-0.priv
        fi
        if [ ! -e config-genesis.batch ]; then
          sawset genesis -k /etc/sawtooth/keys/validator.priv -o config-genesis.batch
        fi
        while [ ! -f /poet-shared/validators/validator-1.pub ] || 
              [ ! -f /poet-shared/validators/validator-2.pub ] || 
              [ ! -f /poet-shared/validators/validator-3.pub ] || 
              [ ! -f /poet-shared/validators/validator-4.pub ]; do
          sleep 1
        done
        if [ ! -e config.batch ]; then
          sawset proposal create \
            -k /etc/sawtooth/keys/validator.priv \
            sawtooth.consensus.algorithm.name=PoET \
            sawtooth.consensus.algorithm.version=0.1 \
            sawtooth.poet.report_public_key_pem=\"$(cat /poet-shared/simulator_rk_pub.pem)\" \
            sawtooth.poet.valid_enclave_measurements=$(cat /poet-shared/poet-enclave-measurement) \
            sawtooth.poet.valid_enclave_basenames=$(cat /poet-shared/poet-enclave-basename) \
            sawtooth.poet.target_wait_time=5 \
            sawtooth.poet.initial_wait_time=25 \
            sawtooth.publisher.max_batches_per_block=100 \
            -o config.batch
        fi
        if [ ! -e /var/lib/sawtooth/genesis.batch ]; then
          sawadm genesis config-genesis.batch config.batch
        fi
        sawtooth-validator -vv \
          --endpoint tcp://validator-0:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --peering static \
          --scheduler parallel \
          --network-auth trust
      "

  validator-1:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-1
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        if [ -e /poet-shared/validators/validator-1.priv ]; then
          cp /poet-shared/validators/validator-1.pub /etc/sawtooth/keys/validator.pub
          cp /poet-shared/validators/validator-1.priv /etc/sawtooth/keys/validator.priv
        fi
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /poet-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /poet-shared/validators/validator-1.pub
          cp /etc/sawtooth/keys/validator.priv /poet-shared/validators/validator-1.priv
        fi
        sawtooth-validator -vv \
          --endpoint tcp://validator-1:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --peering static \
          --peers tcp://validator-0:8800 \
          --scheduler parallel \
          --network-auth trust
      "

  validator-2:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-2
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        if [ -e /poet-shared/validators/validator-2.priv ]; then
          cp /poet-shared/validators/validator-2.pub /etc/sawtooth/keys/validator.pub
          cp /poet-shared/validators/validator-2.priv /etc/sawtooth/keys/validator.priv
        fi
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /poet-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /poet-shared/validators/validator-2.pub
          cp /etc/sawtooth/keys/validator.priv /poet-shared/validators/validator-2.priv
        fi
        sawtooth-validator -vv \
          --endpoint tcp://validator-2:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --peering static \
          --peers tcp://validator-0:8800,tcp://validator-1:8800 \
          --scheduler parallel \
          --network-auth trust
      "

  validator-3:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-3
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        if [ -e /poet-shared/validators/validator-3.priv ]; then
          cp /poet-shared/validators/validator-3.pub /etc/sawtooth/keys/validator.pub
          cp /poet-shared/validators/validator-3.priv /etc/sawtooth/keys/validator.priv
        fi
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /poet-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /poet-shared/validators/validator-3.pub
          cp /etc/sawtooth/keys/validator.priv /poet-shared/validators/validator-3.priv
        fi
        sawtooth-validator -vv \
          --endpoint tcp://validator-3:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --peering static \
          --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-2:8800 \
          --scheduler parallel \
          --network-auth trust
      "

  validator-4:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-4
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        if [ -e /poet-shared/validators/validator-4.priv ]; then
          cp /poet-shared/validators/validator-4.pub /etc/sawtooth/keys/validator.pub
          cp /poet-shared/validators/validator-4.priv /etc/sawtooth/keys/validator.priv
        fi
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /poet-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /poet-shared/validators/validator-4.pub
          cp /etc/sawtooth/keys/validator.priv /poet-shared/validators/validator-4.priv
        fi
        sawtooth-validator -vv \
          --endpoint tcp://validator-4:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --peering static \
          --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-2:8800,tcp://validator-3:8800 \
          --scheduler parallel \
          --network-auth trust
      "

  rest-api-0:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default-0
    expose:
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-0:4004 --bind rest-api-0:8008
    stop_signal: SIGKILL

  rest-api-1:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default-1
    expose:
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-1:4004 --bind rest-api-1:8008
    stop_signal: SIGKILL

  rest-api-2:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default-2
    expose:
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-2:4004 --bind rest-api-2:8008
    stop_signal: SIGKILL

  rest-api-3:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default-3
    expose:
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-3:4004 --bind rest-api-3:8008
    stop_signal: SIGKILL

  rest-api-4:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default-4
    expose:
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-4:4004 --bind rest-api-4:8008
    stop_signal: SIGKILL

  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default-0
    expose:
      - 4004
    command: settings-tp -C tcp://validator-0:4004
    stop_signal: SIGKILL

  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default-1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL

  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default-2
    expose:
      - 4004
    command: settings-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL

  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default-3
    expose:
      - 4004
    command: settings-tp -C tcp://validator-3:4004
    stop_signal: SIGKILL

  settings-tp-4:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default-4
    expose:
      - 4004
    command: settings-tp -C tcp://validator-4:4004
    stop_signal: SIGKILL

  poet-validator-registry-tp-0:
    image: hyperledger/sawtooth-poet-validator-registry-tp:chime
    container_name: sawtooth-poet-validator-registry-tp-0
    expose:
      - 4004
    command: poet-validator-registry-tp -C tcp://validator-0:4004
    stop_signal: SIGKILL

  poet-validator-registry-tp-1:
    image: hyperledger/sawtooth-poet-validator-registry-tp:chime
    container_name: sawtooth-poet-validator-registry-tp-1
    expose:
      - 4004
    command: poet-validator-registry-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL

  poet-validator-registry-tp-2:
    image: hyperledger/sawtooth-poet-validator-registry-tp:chime
    container_name: sawtooth-poet-validator-registry-tp-2
    expose:
      - 4004
    command: poet-validator-registry-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL

  poet-validator-registry-tp-3:
    image: hyperledger/sawtooth-poet-validator-registry-tp:chime
    container_name: sawtooth-poet-validator-registry-tp-3
    expose:
      - 4004
    command: poet-validator-registry-tp -C tcp://validator-3:4004
    stop_signal: SIGKILL

  poet-validator-registry-tp-4:
    image: hyperledger/sawtooth-poet-validator-registry-tp:chime
    container_name: sawtooth-poet-validator-registry-tp-4
    expose:
      - 4004
    command: poet-validator-registry-tp -C tcp://validator-4:4004
    stop_signal: SIGKILL

  poet-engine-0:
    image: hyperledger/sawtooth-poet-engine:chime
    container_name: sawtooth-poet-engine-0
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        if [ ! -f /poet-shared/poet-enclave-measurement ]; then
          poet enclave measurement >> /poet-shared/poet-enclave-measurement
        fi
        if [ ! -f /poet-shared/poet-enclave-basename ]; then
          poet enclave basename >> /poet-shared/poet-enclave-basename
        fi
        if [ ! -f /poet-shared/simulator_rk_pub.pem ]; then
          cp /etc/sawtooth/simulator_rk_pub.pem /poet-shared
        fi
        while [ ! -f /poet-shared/validators/validator-0.priv ]; do sleep 1; done
        cp /poet-shared/validators/validator-0.* /etc/sawtooth/keys/
        poet registration create -k /etc/sawtooth/keys/validator.priv -o /poet-shared/poet.batch
        poet-engine -C tcp://validator-0:5050 --component tcp://validator-0:4004
      "
    stop_signal: SIGKILL

  poet-engine-1:
    image: hyperledger/sawtooth-poet-engine:chime
    container_name: sawtooth-poet-engine-1
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        while [ ! -f /poet-shared/validators/validator-1.priv ]; do sleep 1; done
        cp /poet-shared/validators/validator-1.* /etc/sawtooth/keys/
        poet-engine -C tcp://validator-1:5050 --component tcp://validator-1:4004
      "
    stop_signal: SIGKILL

  poet-engine-2:
    image: hyperledger/sawtooth-poet-engine:chime
    container_name: sawtooth-poet-engine-2
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        while [ ! -f /poet-shared/validators/validator-2.priv ]; do sleep 1; done
        cp /poet-shared/validators/validator-2.* /etc/sawtooth/keys/
        poet-engine -C tcp://validator-2:5050 --component tcp://validator-2:4004
      "
    stop_signal: SIGKILL

  poet-engine-3:
    image: hyperledger/sawtooth-poet-engine:chime
    container_name: sawtooth-poet-engine-3
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        while [ ! -f /poet-shared/validators/validator-3.priv ]; do sleep 1; done
        cp /poet-shared/validators/validator-3.* /etc/sawtooth/keys/
        poet-engine -C tcp://validator-3:5050 --component tcp://validator-3:4004
      "
    stop_signal: SIGKILL

  poet-engine-4:
    image: hyperledger/sawtooth-poet-engine:chime
    container_name: sawtooth-poet-engine-4
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        while [ ! -f /poet-shared/validators/validator-4.priv ]; do sleep 1; done
        cp /poet-shared/validators/validator-4.* /etc/sawtooth/keys/
        poet-engine -C tcp://validator-4:5050 --component tcp://validator-4:4004
      "
    stop_signal: SIGKILL

  xo-tp-0:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-0
    expose:
      - 4004
    command: xo-tp-python -vv -C tcp://validator-0:4004
    stop_signal: SIGKILL

  xo-tp-1:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-1
    expose:
      - 4004
    command: xo-tp-python -vv -C tcp://validator-1:4004
    stop_signal: SIGKILL

  xo-tp-2:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-2
    expose:
      - 4004
    command: xo-tp-python -vv -C tcp://validator-2:4004
    stop_signal: SIGKILL

  xo-tp-3:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-3
    expose:
      - 4004
    command: xo-tp-python -vv -C tcp://validator-3:4004
    stop_signal: SIGKILL

  xo-tp-4:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-4
    expose:
      - 4004
    command: xo-tp-python -vv -C tcp://validator-4:4004
    stop_signal: SIGKILL